In [1]:
import pandas as pd # 以pd别名导入Python数据分析模块
import numpy as np # 导入数值计算模块

In [2]:
reviews = pd.read_csv('./review/reviews_extracted.csv')

# 正面评论

In [3]:
pos = reviews[reviews['sentiment'].str.contains('pos')]

#重新编号
pos = pos.reset_index(drop=True)
pos

,商品名称,评论,cutword,sentiment
0,MatePad 11.5,高清护眼屏，丰富的学习资源，配件可选择性强，搭配之后非常实用，给孩子辅助学习非常方便，真的被...,高清 护眼 屏 学习 资源 配件 可选择性 强 搭配 实用 孩子 辅助 学习 真的 设计 惊艳,pos
1,MatePad 11.5,还在犹豫该不该冲的学生党可以看我这边，完全真实的新机测评！!！真的是百闻不如一记！ 第一次看...,犹豫 该不该 学生 党 真实 新机 测评 真的 百闻不如 一记 第一次 麒麟 系列 快充 一...,pos
2,MatePad 11.5,今天收到宝贝，该说不说.颜值很在线 薄厚适中，手感相当的 系统运行起来比较流畅，关键是价格很...,收到 宝贝 说 说 颜值 在线 薄厚 适中 手感 系统 运行 流畅 关键 价格 亲民 声音 操作,pos
3,MatePad 11.5,外观材质：金属机身凉手哇屏幕效果：清晰通透护眼呀运行速度：麒麟芯片可以呀轻薄程度：轻薄拿着不...,外观 材质 金属 机身 凉手 屏幕 效果 清晰 通透 护眼 运行 速度 麒麟 芯片 轻薄 程...,pos
4,MatePad 11.5,外观设计漂亮，尺寸大小合适，包装仔细完整，宝贝手感不错，感觉很好，发货速度快，服务态度一流，...,外观设计 漂亮 尺寸 大小 合适 包装 仔细 完整 宝贝 手感 不错 感觉 发货 速度 快 ...,pos
...,...,...,...,...
12123,小米Redmi Pad Pro,物流速度特别快，服务态度特别好，而且还能和手机无限互联，键盘用起来也特别顺手，的互联互通做的...,物流 速度 特别 快 服务态度 特别 手机 无限 互联 键盘 特别 顺手 互联互通 做 真的...,pos
12124,小米Redmi Pad SE,价格实惠，运行速度快，小孩子学习用足够，价格实惠，活动力度很大，钢化膜质量好，值得购买欲望都...,价格 实惠 运行 速度 快 小孩子 学习 足够 价格 实惠 活动 力度 很大 钢化 膜 质量...,pos
12125,小米Redmi Pad Pro,外观材质：做工精细屏幕效果：颜色亮丽运行速度：刚刚地轻薄程度：适手其他特色：使用方便音质音效...,外观 材质 做工 精细 屏幕 效果 颜色 亮丽 运行 速度 刚刚 轻薄 程度 适手 特色 使...,pos
12126,小米6Pro,全金属外壳摸上去非常有质感操作体验很丝滑，跟几乎没差价格非常香续航很强，昨晚打了两个多小时王...,全 金属外壳 摸上去 质感 操作 体验 很丝滑 没差 价格 香 续航 很强 昨晚 两个 小时...,pos
12127,小米6Max,的这个性价比真的超级高了，包装精美，物流配送第二天就收到了。手感不错，买来刷视频看的，很耐用...,性价比 真的 超级 高 包装 精美 物流配送 第二天 收到 手感 不错 刷 视频 耐用 反应...,pos

In [4]:
pos.to_csv('./sentiment/pos.csv', index = False, encoding = 'utf-8')

In [5]:
# 仅选取正面分词
pos_cutword = pos["cutword"]
pos_cutword.to_csv('./sentiment/pos_cutword.csv', index = False, header = None, encoding = 'utf-8')

# 负面评论

In [6]:
neg = reviews[reviews['sentiment'].str.contains('neg')]

#重新编号
neg = neg.reset_index(drop=True)
neg

,商品名称,评论,cutword,sentiment
0,MatePad 11.5,快递送的很快，屏幕很清晰，点开提示更新到最新的系统，灰色看起来很高级，喜欢的牌子！！！,快递 送 很快 屏幕 清晰 点开 提示 更新 最新 系统 灰色 高级 喜欢 牌子,neg
1,MatePad 11.5,推荐的皮套严重不符合，搞得我挨退货和折损费,推荐 皮套 符合 搞 挨 退货 折损 费,neg
2,MatePad 11.5,"本来想买.,由于一直断货，忽然发现有货一激动就下单了，收到货才发现是.，上网搜了一下，区别主...",本来 想 断货 发现 有货 激动 下单 收到 货才 发现 上网 搜 区别 分辨率 孩子 上网...,neg
3,MatePad 11.5,收货后使用了几天，评价一下感受。首先是屏幕体验，特地选了柔光板，为了上早教课给娃护眼，这个屏...,收货 几天 评价 感受 屏幕 体验 特地 选 柔 光板 早 教课 娃 护眼 屏幕 确实 不错...,neg
4,MatePad 11.5,电量一点都不耐用，差不多一天充一次，像旧电池一样,电量 一点 耐用 充 旧 电池,neg
...,...,...,...,...
387,小米Redmi Pad Pro,不适合买电子产品，交税离谱加币,适合 电子产品 交税 离谱 加币,neg
388,小米Redmi Pad Pro,不知道玩文字游戏有什么意义，用国补的名义做广告？然后阳奉阴违的不执行，买之前提前问了客服，居...,玩 文字游戏 意义 用国补 名义 做广告 阳奉阴违 执行 提前 问 客服 坑 一环套 一环,neg
389,小米7,物流超级给力，早上拍下晚上送到家就能用上了，体验感完美。比想象中的尺寸大，等保护套、钢化膜到...,物流 超级 给力 早上 拍 晚上 送到 家 体验 感 完美 想象 中 尺寸 保护套 钢化 膜...,neg
390,小米Redmi Pad Pro,买了新出的红米，上午下单傍晚就收到了，收到后马上打开，贴好钢化膜装好保护壳，屏幕显示很好，使...,新出 红米 上午 下单 傍晚 收到 收到 打开 贴 钢化 膜 装好 保护 壳 屏幕显示 满意...,neg
391,小米Redmi Pad SE,这款红米 一是双 的时候下单购买的，双 的价格非常给力，比平时降价了不少。 的存储空间适合老...,这款 红米 一是 双 下单 购买 双 价格 给力 平时 降价 存储空间 适合 老人 看剧 机...,neg

In [7]:
neg.to_csv('./sentiment/neg.csv', index = False, encoding = 'utf-8')

In [8]:
# 仅选取负面分词
neg_cutword = neg["cutword"]
neg_cutword.to_csv('./sentiment/neg_cutword.csv', index = False, header = None, encoding = 'utf-8')